# Generated by Django 3.2.5 on 2021-07-21 15:39

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField()),
                ('slug', models.SlugField(verbose_name='URL')),
                ('image', models.ImageField(upload_to=products.models.upload_to, verbose_name='Imagen')),
                ('popularity', models.PositiveBigIntegerField(default=0, verbose_name='Popularidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
