# Generated by Django 3.2.5 on 2021-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slfa', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
