# Generated by Django 3.2 on 2021-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210721_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Description of the product', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
