# Generated by Django 3.2 on 2021-07-22 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 22, 9, 34, 25, 255582)),
            preserve_default=False,
        ),
    ]
