# Generated by Django 3.2.5 on 2021-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Orden Recivida', max_length=100),
        ),
    ]
