# Generated by Django 3.2 on 2021-07-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factura',
            field=models.BooleanField(default=False),
        ),
    ]
