# Generated by Django 3.2.5 on 2021-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=255, verbose_name='Colonia')),
                ('exterior_number', models.PositiveSmallIntegerField(verbose_name='Número Exterior')),
                ('interior_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número Interior')),
                ('postalcode', models.IntegerField(verbose_name='Zip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
