# Generated by Django 3.2.5 on 2021-07-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(default='fffasd', max_length=255, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
