# Generated by Django 3.2.5 on 2021-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210721_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email'}, max_length=255, unique=True),
        ),
    ]
