# Generated by Django 3.2 on 2021-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postalcode',
            field=models.PositiveIntegerField(verbose_name='Zip'),
        ),
    ]
